// Search
export const GET_CITY_LIST = 'GET_CITY_LIST';
export const GET_SEARCH_PARAMS = 'GET_SEARCH_PARAMS';
export const GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS';
export const UPDATE_SEARCH_BUSES = 'UPDATE_SEARCH_BUSES';

// Seatchart
export const GET_SEATCHART_SUCCESS = 'GET_SEATCHART_SUCCESS'
export const UPDATE_SEAT_SELECTED = 'UPDATE_SEAT_SELECTED'
export const RESET_SEATCHART = 'RESET_SEATCHART'

// Checkout
export const GET_CHECKOUT_SUCCESS = 'GET_CHECKOUT_SUCCESS'