// Search
export const GET_CITY_LIST = 'GET_CITY_LIST';
export const GET_SEARCH_PARAMS = 'GET_SEARCH_PARAMS';
export const GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS';
export const UPDATE_SEARCH_BUSES = 'UPDATE_SEARCH_BUSES';
export const UPDATE_FILTER_DEP = 'UPDATE_FILTER_DEP';
export const UPDATE_FILTER_ARR = 'UPDATE_FILTER_ARR';
export const UPDATE_FILTER_PRICE = 'UPDATE_FILTER_PRICE';
export const UPDATE_FILTER_OPS = 'UPDATE_FILTER_OPS';
export const UPDATE_FILTER_PICK = 'UPDATE_FILTER_PICK';
export const UPDATE_FILTER_DROP = 'UPDATE_FILTER_DROP';
export const UPDATE_FILTER_AMEN = 'UPDATE_FILTER_AMEN';
export const UPDATE_FILTER_COACH = 'UPDATE_FILTER_COACH';
export const UPDATE_FILTER_DEALS = 'UPDATE_FILTER_DEALS';
export const UPDATE_FILTER_MTKT = 'UPDATE_FILTER_MTKT';
export const UPDATE_FILTER_RESET = 'UPDATE_FILTER_RESET';

// Seatchart
export const GET_SEATCHART_SUCCESS = 'GET_SEATCHART_SUCCESS'
export const UPDATE_SEAT_SELECTED = 'UPDATE_SEAT_SELECTED'
export const RESET_SEATCHART = 'RESET_SEATCHART'

// Checkout
export const GET_CHECKOUT_SUCCESS = 'GET_CHECKOUT_SUCCESS'